#!/bin/bash

echo "=== Návod pro publikování na GitHub ==="
echo ""
echo "1. Přihlas se do GitHub CLI:"
echo "   gh auth login"
echo ""
echo "2. Vytvoř nový repozitář:"
echo "   gh repo create mail-sending-problem --public --source=. --remote=origin --push"
echo ""
echo "   Nebo pro privátní repozitář:"
echo "   gh repo create mail-sending-problem --private --source=. --remote=origin --push"
echo ""
echo "3. Alternativně - manuální postup:"
echo "   a) Vytvoř repozitář na github.com"
echo "   b) Přidej remote:"
echo "      git remote add origin https://github.com/YOUR_USERNAME/mail-sending-problem.git"
echo "   c) Pushni kód:"
echo "      git push -u origin main"
echo ""
echo "4. Doporučené - přidej README.md:"
echo "   echo '# Mail Sending Problem Solutions' > README.md"
echo "   echo 'Skripty pro řešení problémů s odesíláním e-mailů přes Postfix' >> README.md"
echo "   git add README.md"
echo "   git commit -m 'Add README'"
echo "   git push"